# Generated by Django 3.2.4 on 2021-07-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helloworld',
            old_name='test',
            new_name='text',
        ),
    ]
